version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tododb
      - JWT_SECRET=your_jwt_secret_key

  postgres:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"  # Expondo para a rede host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      -c listen_addresses='*'
      -c password_encryption=scram-sha-256
      -c shared_preload_libraries='pg_stat_statements'

volumes:
  postgres_data: